
// This file has been generated by the GUI designer. Do not modify.
namespace GeneToAnno
{
	public partial class SampleAllocationWindow
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.ScrolledWindow formMainWindow;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button cancelBut;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Button acceptBut;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GeneToAnno.SampleAllocationWindow
			this.Name = "GeneToAnno.SampleAllocationWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Allocate Sample IDs..");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child GeneToAnno.SampleAllocationWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.formMainWindow = new global::Gtk.ScrolledWindow ();
			this.formMainWindow.CanFocus = true;
			this.formMainWindow.Name = "formMainWindow";
			this.formMainWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.vbox1.Add (this.formMainWindow);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.formMainWindow]));
			w1.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cancelBut = new global::Gtk.Button ();
			this.cancelBut.CanFocus = true;
			this.cancelBut.Name = "cancelBut";
			this.cancelBut.UseUnderline = true;
			this.cancelBut.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
			this.hbox1.Add (this.cancelBut);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cancelBut]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.hbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hseparator1]));
			w3.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.acceptBut = new global::Gtk.Button ();
			this.acceptBut.CanFocus = true;
			this.acceptBut.Name = "acceptBut";
			this.acceptBut.UseUnderline = true;
			this.acceptBut.Label = global::Mono.Unix.Catalog.GetString ("Accept");
			this.hbox1.Add (this.acceptBut);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.acceptBut]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 654;
			this.DefaultHeight = 347;
			this.Show ();
			this.cancelBut.Clicked += new global::System.EventHandler (this.OnCancel);
			this.acceptBut.Clicked += new global::System.EventHandler (this.OnAccept);
		}
	}
}
