
// This file has been generated by the GUI designer. Do not modify.
namespace GeneToAnno
{
	public partial class StatsOutputWindow
	{
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.HSeparator hseparator2;
		
		private global::Gtk.Label rankPairsLabel;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.HSeparator hseparator3;
		
		private global::Gtk.Label groupCountLabel;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.ComboBox covTestCombo;
		
		private global::Gtk.Button covRunTestButton;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.HSeparator hseparator4;
		
		private global::Gtk.Label covStatLabel;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.HSeparator hseparator5;
		
		private global::Gtk.Label covLProbLabel;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.HSeparator hseparator6;
		
		private global::Gtk.Label covRProbLabel;
		
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.VBox vbox9;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label sdfdf;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.ComboBox groupTestCombo;
		
		private global::Gtk.Button groupRunTestButton;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.VBox vbox8;
		
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.HSeparator hseparator7;
		
		private global::Gtk.RadioButton showPRadio;
		
		private global::Gtk.RadioButton showStatRadio;
		
		private global::Gtk.VBox vbox10;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Button closeBut;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GeneToAnno.StatsOutputWindow
			this.Name = "GeneToAnno.StatsOutputWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Rank-Split Statistical Tests");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child GeneToAnno.StatsOutputWindow.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Summary");
			this.vbox4.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			w1.Padding = ((uint)(10));
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of Rank Pairs ");
			this.hbox1.Add (this.label4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label4]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.hbox1.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hseparator2]));
			w3.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.rankPairsLabel = new global::Gtk.Label ();
			this.rankPairsLabel.Name = "rankPairsLabel";
			this.rankPairsLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
			this.hbox1.Add (this.rankPairsLabel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.rankPairsLabel]));
			w4.Position = 2;
			this.vbox4.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of Groups ");
			this.hbox2.Add (this.label5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label5]));
			w6.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.hbox2.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hseparator3]));
			w7.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.groupCountLabel = new global::Gtk.Label ();
			this.groupCountLabel.Name = "groupCountLabel";
			this.groupCountLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
			this.hbox2.Add (this.groupCountLabel);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.groupCountLabel]));
			w8.Position = 2;
			this.vbox4.Add (this.hbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox4]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Covariance/Correlation Between Rank and Output Data");
			this.vbox5.Add (this.label7);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label7]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			w11.Padding = ((uint)(10));
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Select Test Type:");
			this.hbox3.Add (this.label8);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label8]));
			w12.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.covTestCombo = global::Gtk.ComboBox.NewText ();
			this.covTestCombo.Name = "covTestCombo";
			this.hbox3.Add (this.covTestCombo);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.covTestCombo]));
			w13.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.covRunTestButton = new global::Gtk.Button ();
			this.covRunTestButton.CanFocus = true;
			this.covRunTestButton.Name = "covRunTestButton";
			this.covRunTestButton.UseUnderline = true;
			this.covRunTestButton.Label = global::Mono.Unix.Catalog.GetString ("Run Test");
			this.hbox3.Add (this.covRunTestButton);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.covRunTestButton]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.vbox5.Add (this.hbox3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox3]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Statistic");
			this.hbox4.Add (this.label12);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label12]));
			w16.Position = 0;
			w16.Padding = ((uint)(25));
			// Container child hbox4.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator ();
			this.hseparator4.Name = "hseparator4";
			this.hbox4.Add (this.hseparator4);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hseparator4]));
			w17.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.covStatLabel = new global::Gtk.Label ();
			this.covStatLabel.Name = "covStatLabel";
			this.covStatLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
			this.hbox4.Add (this.covStatLabel);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.covStatLabel]));
			w18.Position = 2;
			this.vbox6.Add (this.hbox4);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox4]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Left Probability");
			this.hbox6.Add (this.label13);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label13]));
			w20.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.hseparator5 = new global::Gtk.HSeparator ();
			this.hseparator5.Name = "hseparator5";
			this.hbox6.Add (this.hseparator5);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.hseparator5]));
			w21.Position = 1;
			// Container child hbox6.Gtk.Box+BoxChild
			this.covLProbLabel = new global::Gtk.Label ();
			this.covLProbLabel.Name = "covLProbLabel";
			this.covLProbLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
			this.hbox6.Add (this.covLProbLabel);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.covLProbLabel]));
			w22.Position = 2;
			this.vbox6.Add (this.hbox6);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox6]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Right Probability");
			this.hbox7.Add (this.label14);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label14]));
			w24.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hseparator6 = new global::Gtk.HSeparator ();
			this.hseparator6.Name = "hseparator6";
			this.hbox7.Add (this.hseparator6);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hseparator6]));
			w25.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.covRProbLabel = new global::Gtk.Label ();
			this.covRProbLabel.Name = "covRProbLabel";
			this.covRProbLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("...");
			this.hbox7.Add (this.covRProbLabel);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.covRProbLabel]));
			w26.Position = 2;
			this.vbox6.Add (this.hbox7);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox7]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			this.vbox5.Add (this.vbox6);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vbox6]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			this.vbox2.Add (this.vbox5);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox5]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString (" * indicates the effective p-value for this test");
			this.vbox9.Add (this.label2);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.label2]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.sdfdf = new global::Gtk.Label ();
			this.sdfdf.Name = "sdfdf";
			this.sdfdf.LabelProp = global::Mono.Unix.Catalog.GetString ("Test for Difference Between Groups");
			this.vbox9.Add (this.sdfdf);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.sdfdf]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			w31.Padding = ((uint)(8));
			this.vbox7.Add (this.vbox9);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.vbox9]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			w32.Padding = ((uint)(10));
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Select Test Type:");
			this.hbox8.Add (this.label9);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label9]));
			w33.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.groupTestCombo = global::Gtk.ComboBox.NewText ();
			this.groupTestCombo.Name = "groupTestCombo";
			this.hbox8.Add (this.groupTestCombo);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.groupTestCombo]));
			w34.Position = 1;
			// Container child hbox8.Gtk.Box+BoxChild
			this.groupRunTestButton = new global::Gtk.Button ();
			this.groupRunTestButton.CanFocus = true;
			this.groupRunTestButton.Name = "groupRunTestButton";
			this.groupRunTestButton.UseUnderline = true;
			this.groupRunTestButton.Label = global::Mono.Unix.Catalog.GetString ("Run Test");
			this.hbox8.Add (this.groupRunTestButton);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.groupRunTestButton]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox7.Add (this.hbox8);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox8]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.hseparator7 = new global::Gtk.HSeparator ();
			this.hseparator7.WidthRequest = 200;
			this.hseparator7.Name = "hseparator7";
			this.hbox10.Add (this.hseparator7);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.hseparator7]));
			w37.Position = 0;
			// Container child hbox10.Gtk.Box+BoxChild
			this.showPRadio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Show p-value"));
			this.showPRadio.CanFocus = true;
			this.showPRadio.Name = "showPRadio";
			this.showPRadio.DrawIndicator = true;
			this.showPRadio.UseUnderline = true;
			this.showPRadio.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox10.Add (this.showPRadio);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.showPRadio]));
			w38.Position = 1;
			// Container child hbox10.Gtk.Box+BoxChild
			this.showStatRadio = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Show statistic"));
			this.showStatRadio.CanFocus = true;
			this.showStatRadio.Name = "showStatRadio";
			this.showStatRadio.DrawIndicator = true;
			this.showStatRadio.UseUnderline = true;
			this.showStatRadio.Group = this.showPRadio.Group;
			this.hbox10.Add (this.showStatRadio);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.showStatRadio]));
			w39.Position = 2;
			this.vbox8.Add (this.hbox10);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox10]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			this.vbox8.Add (this.vbox10);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.vbox10]));
			w41.Position = 1;
			this.hbox9.Add (this.vbox8);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.vbox8]));
			w42.Position = 0;
			this.vbox7.Add (this.hbox9);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox9]));
			w43.Position = 2;
			this.vbox2.Add (this.vbox7);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox7]));
			w44.Position = 2;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w45.Position = 0;
			this.vbox3.Add (this.vbox1);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox1]));
			w46.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.hbox5.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.hseparator1]));
			w47.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.closeBut = new global::Gtk.Button ();
			this.closeBut.CanFocus = true;
			this.closeBut.Name = "closeBut";
			this.closeBut.UseUnderline = true;
			this.closeBut.Label = global::Mono.Unix.Catalog.GetString ("Close");
			this.hbox5.Add (this.closeBut);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.closeBut]));
			w48.Position = 1;
			w48.Expand = false;
			w48.Fill = false;
			this.vbox3.Add (this.hbox5);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox5]));
			w49.Position = 1;
			w49.Expand = false;
			w49.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 651;
			this.DefaultHeight = 592;
			this.Show ();
			this.covRunTestButton.Clicked += new global::System.EventHandler (this.OnRunCovTest);
			this.groupRunTestButton.Clicked += new global::System.EventHandler (this.OnRunGroupTest);
			this.closeBut.Clicked += new global::System.EventHandler (this.OnClose);
		}
	}
}
