
// This file has been generated by the GUI designer. Do not modify.
namespace GeneToAnno
{
	public partial class LoaderSettings
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Label label17;
		
		private global::Gtk.Entry gff3MainIDTag;
		
		private global::Gtk.VBox vbox9;
		
		private global::Gtk.VBox vbox11;
		
		private global::Gtk.CheckButton gff3SplitIDCheck;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.Entry gff3SplitCharEntry;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.Entry gff3SplitSubsEntry;
		
		private global::Gtk.VBox vbox12;
		
		private global::Gtk.CheckButton gff3TrimSuffCheck;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.Entry gff3TrimSuffEntry;
		
		private global::Gtk.HBox hbox16;
		
		private global::Gtk.VBox vbox22;
		
		private global::Gtk.VBox vbox17;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.VBox vbox8;
		
		private global::Gtk.VBox vbox13;
		
		private global::Gtk.CheckButton genomeLiteLoadBut;
		
		private global::Gtk.CheckButton genomeLineBreakBut;
		
		private global::Gtk.VBox vbox14;
		
		private global::Gtk.CheckButton genomeSplitBaseIDCheck;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Label label18;
		
		private global::Gtk.Entry genomeSplitCharsEntry;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.Label label19;
		
		private global::Gtk.Entry genomeSplitSubsEntry;
		
		private global::Gtk.VBox vbox15;
		
		private global::Gtk.CheckButton genomeTrimSuffCheck;
		
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.Label label20;
		
		private global::Gtk.Entry genomeTrimSuffEntry;
		
		private global::Gtk.Label loaderLabel;
		
		private global::Gtk.HBox hbox20;
		
		private global::Gtk.VBox vbox24;
		
		private global::Gtk.VBox vbox26;
		
		private global::Gtk.Label label22;
		
		private global::Gtk.HBox hbox21;
		
		private global::Gtk.Label label23;
		
		private global::Gtk.Entry fkpmIDColEntry;
		
		private global::Gtk.CheckButton fkpmUseCuffDiffCheck;
		
		private global::Gtk.VBox vbox25;
		
		private global::Gtk.HBox hbox27;
		
		private global::Gtk.Label label24;
		
		private global::Gtk.Entry fkpmColDelimEntry;
		
		private global::Gtk.HBox hbox26;
		
		private global::Gtk.Label label25;
		
		private global::Gtk.Entry fkpmScoreColEntry;
		
		private global::Gtk.HBox hbox25;
		
		private global::Gtk.Label label26;
		
		private global::Gtk.Entry fkpmHIColEntry;
		
		private global::Gtk.VBox vbox27;
		
		private global::Gtk.HBox hbox24;
		
		private global::Gtk.Label label27;
		
		private global::Gtk.Entry fkpmLOColEntry;
		
		private global::Gtk.HBox hbox23;
		
		private global::Gtk.Label label28;
		
		private global::Gtk.Entry fkpmTestColEntry;
		
		private global::Gtk.HBox hbox22;
		
		private global::Gtk.Label label29;
		
		private global::Gtk.Entry fkpmTestSuccessEntry;
		
		private global::Gtk.VBox vbox28;
		
		private global::Gtk.VBox vbox29;
		
		private global::Gtk.CheckButton fkpmHasHeaderCheck;
		
		private global::Gtk.CheckButton fkpmHasHILOCheck;
		
		private global::Gtk.CheckButton fkpmHasTestCheck;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.HBox hbox30;
		
		private global::Gtk.VBox vbox34;
		
		private global::Gtk.VBox vbox35;
		
		private global::Gtk.Label label34;
		
		private global::Gtk.CheckButton samLoadReadNames;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.HBox hbox17;
		
		private global::Gtk.VBox vbox23;
		
		private global::Gtk.HBox hbox18;
		
		private global::Gtk.CheckButton procUseThreads;
		
		private global::Gtk.HBox hbox19;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Entry procThreadsEntry;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.HBox hbox11;
		
		private global::Gtk.VBox vbox16;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.VBox vbox18;
		
		private global::Gtk.CheckButton gPostMakePromoCheck;
		
		private global::Gtk.HBox hbox12;
		
		private global::Gtk.CheckButton gPostPro1Check;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Entry gPostPro1Entry;
		
		private global::Gtk.HBox hbox13;
		
		private global::Gtk.CheckButton gPostPro2Check;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Entry gPostPro2Entry;
		
		private global::Gtk.VBox vbox19;
		
		private global::Gtk.HBox hbox14;
		
		private global::Gtk.CheckButton gPostPro3Check;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Entry gPostPro3Entry;
		
		private global::Gtk.VBox vbox20;
		
		private global::Gtk.CheckButton gPostMake3FlankCheck;
		
		private global::Gtk.HBox hbox15;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Entry gPost3FlankEntry;
		
		private global::Gtk.VBox vbox21;
		
		private global::Gtk.CheckButton gPostIntronCheck;
		
		private global::Gtk.VBox vbox10;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.ScrolledWindow filterWindow;
		
		private global::Gtk.Button filterRunBut;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.HBox hbox28;
		
		private global::Gtk.VBox vbox30;
		
		private global::Gtk.VBox vbox31;
		
		private global::Gtk.Label label30;
		
		private global::Gtk.CheckButton graphOutProcessCheck;
		
		private global::Gtk.Label label31;
		
		private global::Gtk.VBox vbox36;
		
		private global::Gtk.Label label35;
		
		private global::Gtk.HBox hbox31;
		
		private global::Gtk.VBox vbox37;
		
		private global::Gtk.HBox hbox32;
		
		private global::Gtk.CheckButton graphFromEndCheck;
		
		private global::Gtk.HBox hbox33;
		
		private global::Gtk.Label label36;
		
		private global::Gtk.HSeparator hseparator4;
		
		private global::Gtk.Entry graphBasesEntry;
		
		private global::Gtk.Label label21;
		
		private global::Gtk.HBox hbox29;
		
		private global::Gtk.VBox vbox32;
		
		private global::Gtk.VBox vbox33;
		
		private global::Gtk.Label label32;
		
		private global::Gtk.CheckButton statsNormVarCheck;
		
		private global::Gtk.Label label33;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button mainCancel;
		
		private global::Gtk.Button mainAccept;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GeneToAnno.LoaderSettings
			this.Name = "GeneToAnno.LoaderSettings";
			this.Title = global::Mono.Unix.Catalog.GetString ("Program Settings");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child GeneToAnno.LoaderSettings.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 5;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.WidthRequest = 250;
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("GFF3");
			this.label5.UseUnderline = true;
			this.vbox5.Add (this.label5);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label5]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Main gene ID Tag:                                   ");
			this.hbox7.Add (this.label17);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label17]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.gff3MainIDTag = new global::Gtk.Entry ();
			this.gff3MainIDTag.CanFocus = true;
			this.gff3MainIDTag.Name = "gff3MainIDTag";
			this.gff3MainIDTag.IsEditable = true;
			this.gff3MainIDTag.InvisibleChar = '•';
			this.hbox7.Add (this.gff3MainIDTag);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.gff3MainIDTag]));
			w3.Position = 1;
			this.vbox5.Add (this.hbox7);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox7]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox4.Add (this.vbox5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.vbox5]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox4]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.gff3SplitIDCheck = new global::Gtk.CheckButton ();
			this.gff3SplitIDCheck.CanFocus = true;
			this.gff3SplitIDCheck.Name = "gff3SplitIDCheck";
			this.gff3SplitIDCheck.Label = global::Mono.Unix.Catalog.GetString ("Split base gene ID?");
			this.gff3SplitIDCheck.DrawIndicator = true;
			this.gff3SplitIDCheck.UseUnderline = true;
			this.vbox11.Add (this.gff3SplitIDCheck);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.gff3SplitIDCheck]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Split character(s) (';' separated): ");
			this.hbox4.Add (this.label14);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label14]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.gff3SplitCharEntry = new global::Gtk.Entry ();
			this.gff3SplitCharEntry.CanFocus = true;
			this.gff3SplitCharEntry.Name = "gff3SplitCharEntry";
			this.gff3SplitCharEntry.IsEditable = true;
			this.gff3SplitCharEntry.InvisibleChar = '•';
			this.hbox4.Add (this.gff3SplitCharEntry);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.gff3SplitCharEntry]));
			w9.Position = 1;
			this.vbox11.Add (this.hbox4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox4]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Select which substring (1,2,3...):   ");
			this.hbox5.Add (this.label15);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label15]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.gff3SplitSubsEntry = new global::Gtk.Entry ();
			this.gff3SplitSubsEntry.CanFocus = true;
			this.gff3SplitSubsEntry.Name = "gff3SplitSubsEntry";
			this.gff3SplitSubsEntry.IsEditable = true;
			this.gff3SplitSubsEntry.InvisibleChar = '•';
			this.hbox5.Add (this.gff3SplitSubsEntry);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.gff3SplitSubsEntry]));
			w12.Position = 1;
			this.vbox11.Add (this.hbox5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox5]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox9.Add (this.vbox11);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vbox11]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.gff3TrimSuffCheck = new global::Gtk.CheckButton ();
			this.gff3TrimSuffCheck.CanFocus = true;
			this.gff3TrimSuffCheck.Name = "gff3TrimSuffCheck";
			this.gff3TrimSuffCheck.Label = global::Mono.Unix.Catalog.GetString ("Trim Gene ID Suffix/Prefix?");
			this.gff3TrimSuffCheck.DrawIndicator = true;
			this.gff3TrimSuffCheck.UseUnderline = true;
			this.vbox12.Add (this.gff3TrimSuffCheck);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.gff3TrimSuffCheck]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Text to Trim (';' separated):            ");
			this.hbox6.Add (this.label16);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label16]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.gff3TrimSuffEntry = new global::Gtk.Entry ();
			this.gff3TrimSuffEntry.CanFocus = true;
			this.gff3TrimSuffEntry.Name = "gff3TrimSuffEntry";
			this.gff3TrimSuffEntry.IsEditable = true;
			this.gff3TrimSuffEntry.InvisibleChar = '•';
			this.hbox6.Add (this.gff3TrimSuffEntry);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.gff3TrimSuffEntry]));
			w17.Position = 1;
			this.vbox12.Add (this.hbox6);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox6]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox ();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.vbox22 = new global::Gtk.VBox ();
			this.vbox22.Name = "vbox22";
			this.vbox22.Spacing = 6;
			this.hbox16.Add (this.vbox22);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.vbox22]));
			w19.Position = 1;
			this.vbox12.Add (this.hbox16);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox16]));
			w20.Position = 2;
			this.vbox9.Add (this.vbox12);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.vbox12]));
			w21.Position = 1;
			this.vbox2.Add (this.vbox9);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox9]));
			w22.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox17 = new global::Gtk.VBox ();
			this.vbox17.Name = "vbox17";
			this.vbox17.Spacing = 6;
			this.vbox2.Add (this.vbox17);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox17]));
			w23.Position = 2;
			this.hbox2.Add (this.vbox2);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox2]));
			w24.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.WidthRequest = 250;
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Genome");
			this.vbox6.Add (this.label7);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label7]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox ();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.genomeLiteLoadBut = new global::Gtk.CheckButton ();
			this.genomeLiteLoadBut.CanFocus = true;
			this.genomeLiteLoadBut.Name = "genomeLiteLoadBut";
			this.genomeLiteLoadBut.Label = global::Mono.Unix.Catalog.GetString ("Lite Load? (no-seq data)");
			this.genomeLiteLoadBut.DrawIndicator = true;
			this.genomeLiteLoadBut.UseUnderline = true;
			this.vbox13.Add (this.genomeLiteLoadBut);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.genomeLiteLoadBut]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.genomeLineBreakBut = new global::Gtk.CheckButton ();
			this.genomeLineBreakBut.CanFocus = true;
			this.genomeLineBreakBut.Name = "genomeLineBreakBut";
			this.genomeLineBreakBut.Label = global::Mono.Unix.Catalog.GetString ("Line-breaks in seq?");
			this.genomeLineBreakBut.DrawIndicator = true;
			this.genomeLineBreakBut.UseUnderline = true;
			this.vbox13.Add (this.genomeLineBreakBut);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.genomeLineBreakBut]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.vbox14 = new global::Gtk.VBox ();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.genomeSplitBaseIDCheck = new global::Gtk.CheckButton ();
			this.genomeSplitBaseIDCheck.CanFocus = true;
			this.genomeSplitBaseIDCheck.Name = "genomeSplitBaseIDCheck";
			this.genomeSplitBaseIDCheck.Label = global::Mono.Unix.Catalog.GetString ("Split Base Scaffold ID?");
			this.genomeSplitBaseIDCheck.DrawIndicator = true;
			this.genomeSplitBaseIDCheck.UseUnderline = true;
			this.vbox14.Add (this.genomeSplitBaseIDCheck);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.genomeSplitBaseIDCheck]));
			w28.Position = 0;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Split character(s) (';' separated): ");
			this.hbox8.Add (this.label18);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label18]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.genomeSplitCharsEntry = new global::Gtk.Entry ();
			this.genomeSplitCharsEntry.CanFocus = true;
			this.genomeSplitCharsEntry.Name = "genomeSplitCharsEntry";
			this.genomeSplitCharsEntry.IsEditable = true;
			this.genomeSplitCharsEntry.InvisibleChar = '•';
			this.hbox8.Add (this.genomeSplitCharsEntry);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.genomeSplitCharsEntry]));
			w30.Position = 1;
			this.vbox14.Add (this.hbox8);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox8]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Select which substring (1,2,3...):   ");
			this.hbox9.Add (this.label19);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label19]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.genomeSplitSubsEntry = new global::Gtk.Entry ();
			this.genomeSplitSubsEntry.CanFocus = true;
			this.genomeSplitSubsEntry.Name = "genomeSplitSubsEntry";
			this.genomeSplitSubsEntry.IsEditable = true;
			this.genomeSplitSubsEntry.InvisibleChar = '•';
			this.hbox9.Add (this.genomeSplitSubsEntry);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.genomeSplitSubsEntry]));
			w33.Position = 1;
			this.vbox14.Add (this.hbox9);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox14 [this.hbox9]));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			this.vbox13.Add (this.vbox14);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.vbox14]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox8.Add (this.vbox13);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.vbox13]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			this.hbox3.Add (this.vbox8);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox8]));
			w37.Position = 0;
			this.vbox6.Add (this.hbox3);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox3]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			this.vbox3.Add (this.vbox6);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox6]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox15 = new global::Gtk.VBox ();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.genomeTrimSuffCheck = new global::Gtk.CheckButton ();
			this.genomeTrimSuffCheck.CanFocus = true;
			this.genomeTrimSuffCheck.Name = "genomeTrimSuffCheck";
			this.genomeTrimSuffCheck.Label = global::Mono.Unix.Catalog.GetString ("Trim Scaffold ID Suffix/Prefix?");
			this.genomeTrimSuffCheck.DrawIndicator = true;
			this.genomeTrimSuffCheck.UseUnderline = true;
			this.vbox15.Add (this.genomeTrimSuffCheck);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.genomeTrimSuffCheck]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Text To Trim (';' separated):            ");
			this.hbox10.Add (this.label20);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label20]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.genomeTrimSuffEntry = new global::Gtk.Entry ();
			this.genomeTrimSuffEntry.CanFocus = true;
			this.genomeTrimSuffEntry.Name = "genomeTrimSuffEntry";
			this.genomeTrimSuffEntry.IsEditable = true;
			this.genomeTrimSuffEntry.InvisibleChar = '•';
			this.hbox10.Add (this.genomeTrimSuffEntry);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.genomeTrimSuffEntry]));
			w42.Position = 1;
			this.vbox15.Add (this.hbox10);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.hbox10]));
			w43.Position = 1;
			w43.Expand = false;
			w43.Fill = false;
			this.vbox3.Add (this.vbox15);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox15]));
			w44.Position = 1;
			w44.Expand = false;
			w44.Fill = false;
			this.hbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox3]));
			w45.Position = 1;
			this.notebook1.Add (this.hbox2);
			// Notebook tab
			this.loaderLabel = new global::Gtk.Label ();
			this.loaderLabel.Name = "loaderLabel";
			this.loaderLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Loader");
			this.notebook1.SetTabLabel (this.hbox2, this.loaderLabel);
			this.loaderLabel.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.hbox20 = new global::Gtk.HBox ();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.vbox24 = new global::Gtk.VBox ();
			this.vbox24.WidthRequest = 350;
			this.vbox24.Name = "vbox24";
			this.vbox24.Spacing = 6;
			// Container child vbox24.Gtk.Box+BoxChild
			this.vbox26 = new global::Gtk.VBox ();
			this.vbox26.Name = "vbox26";
			this.vbox26.Spacing = 6;
			// Container child vbox26.Gtk.Box+BoxChild
			this.label22 = new global::Gtk.Label ();
			this.label22.Name = "label22";
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("FKPM File Options/Specifications");
			this.vbox26.Add (this.label22);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox26 [this.label22]));
			w47.Position = 0;
			w47.Expand = false;
			w47.Fill = false;
			w47.Padding = ((uint)(5));
			// Container child vbox26.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox ();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.Xpad = 5;
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("ID Column (Zero-Index): ");
			this.hbox21.Add (this.label23);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.label23]));
			w48.Position = 0;
			w48.Expand = false;
			w48.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.fkpmIDColEntry = new global::Gtk.Entry ();
			this.fkpmIDColEntry.WidthRequest = 100;
			this.fkpmIDColEntry.CanFocus = true;
			this.fkpmIDColEntry.Name = "fkpmIDColEntry";
			this.fkpmIDColEntry.IsEditable = true;
			this.fkpmIDColEntry.InvisibleChar = '•';
			this.hbox21.Add (this.fkpmIDColEntry);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.fkpmIDColEntry]));
			w49.PackType = ((global::Gtk.PackType)(1));
			w49.Position = 1;
			w49.Expand = false;
			this.vbox26.Add (this.hbox21);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox26 [this.hbox21]));
			w50.Position = 1;
			w50.Expand = false;
			w50.Fill = false;
			// Container child vbox26.Gtk.Box+BoxChild
			this.fkpmUseCuffDiffCheck = new global::Gtk.CheckButton ();
			this.fkpmUseCuffDiffCheck.CanFocus = true;
			this.fkpmUseCuffDiffCheck.Name = "fkpmUseCuffDiffCheck";
			this.fkpmUseCuffDiffCheck.Label = global::Mono.Unix.Catalog.GetString ("Use file that isn't Cuff-diff output?");
			this.fkpmUseCuffDiffCheck.DrawIndicator = true;
			this.fkpmUseCuffDiffCheck.UseUnderline = true;
			this.vbox26.Add (this.fkpmUseCuffDiffCheck);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox26 [this.fkpmUseCuffDiffCheck]));
			w51.Position = 2;
			w51.Expand = false;
			w51.Fill = false;
			this.vbox24.Add (this.vbox26);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox24 [this.vbox26]));
			w52.Position = 0;
			w52.Expand = false;
			w52.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.vbox25 = new global::Gtk.VBox ();
			this.vbox25.Name = "vbox25";
			this.vbox25.Spacing = 6;
			// Container child vbox25.Gtk.Box+BoxChild
			this.hbox27 = new global::Gtk.HBox ();
			this.hbox27.Name = "hbox27";
			this.hbox27.Spacing = 6;
			// Container child hbox27.Gtk.Box+BoxChild
			this.label24 = new global::Gtk.Label ();
			this.label24.Name = "label24";
			this.label24.Xpad = 5;
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("Column Delimitor: ");
			this.hbox27.Add (this.label24);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox27 [this.label24]));
			w53.Position = 0;
			w53.Expand = false;
			w53.Fill = false;
			// Container child hbox27.Gtk.Box+BoxChild
			this.fkpmColDelimEntry = new global::Gtk.Entry ();
			this.fkpmColDelimEntry.WidthRequest = 100;
			this.fkpmColDelimEntry.CanFocus = true;
			this.fkpmColDelimEntry.Name = "fkpmColDelimEntry";
			this.fkpmColDelimEntry.IsEditable = true;
			this.fkpmColDelimEntry.InvisibleChar = '•';
			this.hbox27.Add (this.fkpmColDelimEntry);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox27 [this.fkpmColDelimEntry]));
			w54.PackType = ((global::Gtk.PackType)(1));
			w54.Position = 1;
			w54.Expand = false;
			this.vbox25.Add (this.hbox27);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox25 [this.hbox27]));
			w55.Position = 0;
			w55.Expand = false;
			w55.Fill = false;
			// Container child vbox25.Gtk.Box+BoxChild
			this.hbox26 = new global::Gtk.HBox ();
			this.hbox26.Name = "hbox26";
			this.hbox26.Spacing = 6;
			// Container child hbox26.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label ();
			this.label25.Name = "label25";
			this.label25.Xpad = 5;
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("First FKPM Score Column:");
			this.hbox26.Add (this.label25);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.label25]));
			w56.Position = 0;
			w56.Expand = false;
			w56.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.fkpmScoreColEntry = new global::Gtk.Entry ();
			this.fkpmScoreColEntry.WidthRequest = 100;
			this.fkpmScoreColEntry.CanFocus = true;
			this.fkpmScoreColEntry.Name = "fkpmScoreColEntry";
			this.fkpmScoreColEntry.IsEditable = true;
			this.fkpmScoreColEntry.InvisibleChar = '•';
			this.hbox26.Add (this.fkpmScoreColEntry);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.fkpmScoreColEntry]));
			w57.PackType = ((global::Gtk.PackType)(1));
			w57.Position = 1;
			w57.Expand = false;
			w57.Fill = false;
			this.vbox25.Add (this.hbox26);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox25 [this.hbox26]));
			w58.Position = 1;
			w58.Expand = false;
			w58.Fill = false;
			// Container child vbox25.Gtk.Box+BoxChild
			this.hbox25 = new global::Gtk.HBox ();
			this.hbox25.Name = "hbox25";
			this.hbox25.Spacing = 6;
			// Container child hbox25.Gtk.Box+BoxChild
			this.label26 = new global::Gtk.Label ();
			this.label26.Name = "label26";
			this.label26.Xpad = 5;
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("(Op) First 'HI' Score Column: ");
			this.hbox25.Add (this.label26);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.label26]));
			w59.Position = 0;
			w59.Expand = false;
			w59.Fill = false;
			// Container child hbox25.Gtk.Box+BoxChild
			this.fkpmHIColEntry = new global::Gtk.Entry ();
			this.fkpmHIColEntry.WidthRequest = 100;
			this.fkpmHIColEntry.CanFocus = true;
			this.fkpmHIColEntry.Name = "fkpmHIColEntry";
			this.fkpmHIColEntry.IsEditable = true;
			this.fkpmHIColEntry.InvisibleChar = '•';
			this.hbox25.Add (this.fkpmHIColEntry);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.fkpmHIColEntry]));
			w60.PackType = ((global::Gtk.PackType)(1));
			w60.Position = 1;
			w60.Expand = false;
			this.vbox25.Add (this.hbox25);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbox25 [this.hbox25]));
			w61.Position = 2;
			w61.Expand = false;
			w61.Fill = false;
			this.vbox24.Add (this.vbox25);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox24 [this.vbox25]));
			w62.Position = 1;
			w62.Expand = false;
			w62.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.vbox27 = new global::Gtk.VBox ();
			this.vbox27.Name = "vbox27";
			this.vbox27.Spacing = 6;
			// Container child vbox27.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox ();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.label27 = new global::Gtk.Label ();
			this.label27.Name = "label27";
			this.label27.Xpad = 5;
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString ("(Op) First 'LO' Score Column: ");
			this.hbox24.Add (this.label27);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.label27]));
			w63.Position = 0;
			w63.Expand = false;
			w63.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.fkpmLOColEntry = new global::Gtk.Entry ();
			this.fkpmLOColEntry.WidthRequest = 100;
			this.fkpmLOColEntry.CanFocus = true;
			this.fkpmLOColEntry.Name = "fkpmLOColEntry";
			this.fkpmLOColEntry.IsEditable = true;
			this.fkpmLOColEntry.InvisibleChar = '•';
			this.hbox24.Add (this.fkpmLOColEntry);
			global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.fkpmLOColEntry]));
			w64.PackType = ((global::Gtk.PackType)(1));
			w64.Position = 1;
			w64.Expand = false;
			this.vbox27.Add (this.hbox24);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox27 [this.hbox24]));
			w65.Position = 0;
			w65.Expand = false;
			w65.Fill = false;
			// Container child vbox27.Gtk.Box+BoxChild
			this.hbox23 = new global::Gtk.HBox ();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.label28 = new global::Gtk.Label ();
			this.label28.Name = "label28";
			this.label28.Xpad = 5;
			this.label28.LabelProp = global::Mono.Unix.Catalog.GetString ("(Op) First Test Pass/Fail Column: ");
			this.hbox23.Add (this.label28);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.label28]));
			w66.Position = 0;
			w66.Expand = false;
			w66.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.fkpmTestColEntry = new global::Gtk.Entry ();
			this.fkpmTestColEntry.WidthRequest = 100;
			this.fkpmTestColEntry.CanFocus = true;
			this.fkpmTestColEntry.Name = "fkpmTestColEntry";
			this.fkpmTestColEntry.IsEditable = true;
			this.fkpmTestColEntry.InvisibleChar = '•';
			this.hbox23.Add (this.fkpmTestColEntry);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.fkpmTestColEntry]));
			w67.PackType = ((global::Gtk.PackType)(1));
			w67.Position = 1;
			w67.Expand = false;
			this.vbox27.Add (this.hbox23);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.vbox27 [this.hbox23]));
			w68.Position = 1;
			w68.Expand = false;
			w68.Fill = false;
			// Container child vbox27.Gtk.Box+BoxChild
			this.hbox22 = new global::Gtk.HBox ();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.label29 = new global::Gtk.Label ();
			this.label29.Name = "label29";
			this.label29.Xpad = 5;
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString ("(Op) Test Successful Text: ");
			this.hbox22.Add (this.label29);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.label29]));
			w69.Position = 0;
			w69.Expand = false;
			w69.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.fkpmTestSuccessEntry = new global::Gtk.Entry ();
			this.fkpmTestSuccessEntry.WidthRequest = 100;
			this.fkpmTestSuccessEntry.CanFocus = true;
			this.fkpmTestSuccessEntry.Name = "fkpmTestSuccessEntry";
			this.fkpmTestSuccessEntry.IsEditable = true;
			this.fkpmTestSuccessEntry.InvisibleChar = '•';
			this.hbox22.Add (this.fkpmTestSuccessEntry);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.fkpmTestSuccessEntry]));
			w70.PackType = ((global::Gtk.PackType)(1));
			w70.Position = 1;
			w70.Expand = false;
			this.vbox27.Add (this.hbox22);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.vbox27 [this.hbox22]));
			w71.Position = 2;
			w71.Expand = false;
			w71.Fill = false;
			this.vbox24.Add (this.vbox27);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbox24 [this.vbox27]));
			w72.Position = 2;
			w72.Expand = false;
			w72.Fill = false;
			this.hbox20.Add (this.vbox24);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.vbox24]));
			w73.Position = 0;
			w73.Expand = false;
			w73.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.vbox28 = new global::Gtk.VBox ();
			this.vbox28.Name = "vbox28";
			this.vbox28.Spacing = 6;
			// Container child vbox28.Gtk.Box+BoxChild
			this.vbox29 = new global::Gtk.VBox ();
			this.vbox29.Name = "vbox29";
			this.vbox29.Spacing = 6;
			// Container child vbox29.Gtk.Box+BoxChild
			this.fkpmHasHeaderCheck = new global::Gtk.CheckButton ();
			this.fkpmHasHeaderCheck.CanFocus = true;
			this.fkpmHasHeaderCheck.Name = "fkpmHasHeaderCheck";
			this.fkpmHasHeaderCheck.Label = global::Mono.Unix.Catalog.GetString ("File Has Header");
			this.fkpmHasHeaderCheck.DrawIndicator = true;
			this.fkpmHasHeaderCheck.UseUnderline = true;
			this.fkpmHasHeaderCheck.BorderWidth = ((uint)(20));
			this.vbox29.Add (this.fkpmHasHeaderCheck);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vbox29 [this.fkpmHasHeaderCheck]));
			w74.Position = 1;
			w74.Expand = false;
			w74.Fill = false;
			this.vbox28.Add (this.vbox29);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox28 [this.vbox29]));
			w75.Position = 0;
			// Container child vbox28.Gtk.Box+BoxChild
			this.fkpmHasHILOCheck = new global::Gtk.CheckButton ();
			this.fkpmHasHILOCheck.CanFocus = true;
			this.fkpmHasHILOCheck.Name = "fkpmHasHILOCheck";
			this.fkpmHasHILOCheck.Label = global::Mono.Unix.Catalog.GetString ("File Has Hi-Lo scores");
			this.fkpmHasHILOCheck.DrawIndicator = true;
			this.fkpmHasHILOCheck.UseUnderline = true;
			this.fkpmHasHILOCheck.Xalign = 0.1F;
			this.fkpmHasHILOCheck.BorderWidth = ((uint)(20));
			this.vbox28.Add (this.fkpmHasHILOCheck);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.vbox28 [this.fkpmHasHILOCheck]));
			w76.Position = 1;
			w76.Expand = false;
			w76.Fill = false;
			// Container child vbox28.Gtk.Box+BoxChild
			this.fkpmHasTestCheck = new global::Gtk.CheckButton ();
			this.fkpmHasTestCheck.CanFocus = true;
			this.fkpmHasTestCheck.Name = "fkpmHasTestCheck";
			this.fkpmHasTestCheck.Label = global::Mono.Unix.Catalog.GetString ("File Has Test Status Column");
			this.fkpmHasTestCheck.DrawIndicator = true;
			this.fkpmHasTestCheck.UseUnderline = true;
			this.fkpmHasTestCheck.BorderWidth = ((uint)(20));
			this.vbox28.Add (this.fkpmHasTestCheck);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.vbox28 [this.fkpmHasTestCheck]));
			w77.Position = 2;
			w77.Expand = false;
			w77.Fill = false;
			this.hbox20.Add (this.vbox28);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.vbox28]));
			w78.Position = 1;
			this.notebook1.Add (this.hbox20);
			global::Gtk.Notebook.NotebookChild w79 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.hbox20]));
			w79.Position = 1;
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Loader2");
			this.notebook1.SetTabLabel (this.hbox20, this.label1);
			this.label1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.hbox30 = new global::Gtk.HBox ();
			this.hbox30.Name = "hbox30";
			this.hbox30.Spacing = 6;
			// Container child hbox30.Gtk.Box+BoxChild
			this.vbox34 = new global::Gtk.VBox ();
			this.vbox34.Name = "vbox34";
			this.vbox34.Spacing = 6;
			// Container child vbox34.Gtk.Box+BoxChild
			this.vbox35 = new global::Gtk.VBox ();
			this.vbox35.Name = "vbox35";
			this.vbox35.Spacing = 6;
			// Container child vbox35.Gtk.Box+BoxChild
			this.label34 = new global::Gtk.Label ();
			this.label34.Name = "label34";
			this.label34.Xpad = 50;
			this.label34.LabelProp = global::Mono.Unix.Catalog.GetString ("SAM file loading Options");
			this.vbox35.Add (this.label34);
			global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.vbox35 [this.label34]));
			w80.Position = 0;
			w80.Expand = false;
			w80.Fill = false;
			w80.Padding = ((uint)(5));
			// Container child vbox35.Gtk.Box+BoxChild
			this.samLoadReadNames = new global::Gtk.CheckButton ();
			this.samLoadReadNames.CanFocus = true;
			this.samLoadReadNames.Name = "samLoadReadNames";
			this.samLoadReadNames.Label = global::Mono.Unix.Catalog.GetString ("Load Individual Read Names (allows output)");
			this.samLoadReadNames.DrawIndicator = true;
			this.samLoadReadNames.UseUnderline = true;
			this.vbox35.Add (this.samLoadReadNames);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.vbox35 [this.samLoadReadNames]));
			w81.Position = 1;
			w81.Expand = false;
			w81.Fill = false;
			this.vbox34.Add (this.vbox35);
			global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.vbox34 [this.vbox35]));
			w82.Position = 0;
			this.hbox30.Add (this.vbox34);
			global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.hbox30 [this.vbox34]));
			w83.Position = 0;
			w83.Expand = false;
			w83.Fill = false;
			this.notebook1.Add (this.hbox30);
			global::Gtk.Notebook.NotebookChild w84 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.hbox30]));
			w84.Position = 2;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("SAM loader");
			this.notebook1.SetTabLabel (this.hbox30, this.label3);
			this.label3.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.hbox17 = new global::Gtk.HBox ();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.vbox23 = new global::Gtk.VBox ();
			this.vbox23.Name = "vbox23";
			this.vbox23.Spacing = 6;
			// Container child vbox23.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox ();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.procUseThreads = new global::Gtk.CheckButton ();
			this.procUseThreads.CanFocus = true;
			this.procUseThreads.Name = "procUseThreads";
			this.procUseThreads.Label = global::Mono.Unix.Catalog.GetString ("Use MultiThreading");
			this.procUseThreads.DrawIndicator = true;
			this.procUseThreads.UseUnderline = true;
			this.procUseThreads.BorderWidth = ((uint)(5));
			this.hbox18.Add (this.procUseThreads);
			global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.procUseThreads]));
			w85.Position = 0;
			w85.Padding = ((uint)(5));
			this.vbox23.Add (this.hbox18);
			global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.vbox23 [this.hbox18]));
			w86.Position = 0;
			w86.Expand = false;
			w86.Fill = false;
			// Container child vbox23.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox ();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Max Threads To Use: ");
			this.hbox19.Add (this.label12);
			global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.label12]));
			w87.Position = 0;
			w87.Expand = false;
			w87.Fill = false;
			w87.Padding = ((uint)(5));
			// Container child hbox19.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.WidthRequest = 70;
			this.hseparator1.Name = "hseparator1";
			this.hbox19.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.hseparator1]));
			w88.Position = 1;
			// Container child hbox19.Gtk.Box+BoxChild
			this.procThreadsEntry = new global::Gtk.Entry ();
			this.procThreadsEntry.CanFocus = true;
			this.procThreadsEntry.Name = "procThreadsEntry";
			this.procThreadsEntry.IsEditable = true;
			this.procThreadsEntry.InvisibleChar = '•';
			this.hbox19.Add (this.procThreadsEntry);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.procThreadsEntry]));
			w89.Position = 2;
			this.vbox23.Add (this.hbox19);
			global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.vbox23 [this.hbox19]));
			w90.Position = 1;
			w90.Expand = false;
			w90.Fill = false;
			this.hbox17.Add (this.vbox23);
			global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.vbox23]));
			w91.Position = 0;
			w91.Expand = false;
			w91.Fill = false;
			this.notebook1.Add (this.hbox17);
			global::Gtk.Notebook.NotebookChild w92 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.hbox17]));
			w92.Position = 3;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Processing");
			this.notebook1.SetTabLabel (this.hbox17, this.label2);
			this.label2.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.vbox16 = new global::Gtk.VBox ();
			this.vbox16.Name = "vbox16";
			this.vbox16.Spacing = 6;
			// Container child vbox16.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("GFF3 Post-Processing");
			this.vbox16.Add (this.label4);
			global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.label4]));
			w93.Position = 0;
			w93.Expand = false;
			w93.Fill = false;
			w93.Padding = ((uint)(5));
			// Container child vbox16.Gtk.Box+BoxChild
			this.vbox18 = new global::Gtk.VBox ();
			this.vbox18.Name = "vbox18";
			this.vbox18.Spacing = 6;
			// Container child vbox18.Gtk.Box+BoxChild
			this.gPostMakePromoCheck = new global::Gtk.CheckButton ();
			this.gPostMakePromoCheck.CanFocus = true;
			this.gPostMakePromoCheck.Name = "gPostMakePromoCheck";
			this.gPostMakePromoCheck.Label = global::Mono.Unix.Catalog.GetString ("Generate Hypothetical Promotor Regions");
			this.gPostMakePromoCheck.Active = true;
			this.gPostMakePromoCheck.DrawIndicator = true;
			this.gPostMakePromoCheck.UseUnderline = true;
			this.vbox18.Add (this.gPostMakePromoCheck);
			global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.vbox18 [this.gPostMakePromoCheck]));
			w94.Position = 0;
			w94.Expand = false;
			w94.Fill = false;
			// Container child vbox18.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.gPostPro1Check = new global::Gtk.CheckButton ();
			this.gPostPro1Check.CanFocus = true;
			this.gPostPro1Check.Name = "gPostPro1Check";
			this.gPostPro1Check.Label = global::Mono.Unix.Catalog.GetString ("Promotor 1");
			this.gPostPro1Check.DrawIndicator = true;
			this.gPostPro1Check.UseUnderline = true;
			this.hbox12.Add (this.gPostPro1Check);
			global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.gPostPro1Check]));
			w95.Position = 0;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xpad = 10;
			this.label6.Xalign = 0.28F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Size (bp): ");
			this.hbox12.Add (this.label6);
			global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label6]));
			w96.Position = 1;
			w96.Expand = false;
			w96.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.gPostPro1Entry = new global::Gtk.Entry ();
			this.gPostPro1Entry.CanFocus = true;
			this.gPostPro1Entry.Name = "gPostPro1Entry";
			this.gPostPro1Entry.IsEditable = true;
			this.gPostPro1Entry.InvisibleChar = '•';
			this.hbox12.Add (this.gPostPro1Entry);
			global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.gPostPro1Entry]));
			w97.Position = 2;
			this.vbox18.Add (this.hbox12);
			global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.vbox18 [this.hbox12]));
			w98.Position = 1;
			w98.Expand = false;
			w98.Fill = false;
			// Container child vbox18.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.gPostPro2Check = new global::Gtk.CheckButton ();
			this.gPostPro2Check.CanFocus = true;
			this.gPostPro2Check.Name = "gPostPro2Check";
			this.gPostPro2Check.Label = global::Mono.Unix.Catalog.GetString ("Promotor 2");
			this.gPostPro2Check.DrawIndicator = true;
			this.gPostPro2Check.UseUnderline = true;
			this.hbox13.Add (this.gPostPro2Check);
			global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.gPostPro2Check]));
			w99.Position = 0;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xpad = 10;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Size (bp): ");
			this.hbox13.Add (this.label8);
			global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label8]));
			w100.Position = 1;
			w100.Expand = false;
			w100.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.gPostPro2Entry = new global::Gtk.Entry ();
			this.gPostPro2Entry.CanFocus = true;
			this.gPostPro2Entry.Name = "gPostPro2Entry";
			this.gPostPro2Entry.IsEditable = true;
			this.gPostPro2Entry.InvisibleChar = '•';
			this.hbox13.Add (this.gPostPro2Entry);
			global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.gPostPro2Entry]));
			w101.Position = 2;
			this.vbox18.Add (this.hbox13);
			global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.vbox18 [this.hbox13]));
			w102.Position = 2;
			w102.Expand = false;
			w102.Fill = false;
			this.vbox16.Add (this.vbox18);
			global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.vbox18]));
			w103.Position = 1;
			w103.Expand = false;
			w103.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.vbox19 = new global::Gtk.VBox ();
			this.vbox19.Name = "vbox19";
			this.vbox19.Spacing = 6;
			// Container child vbox19.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.gPostPro3Check = new global::Gtk.CheckButton ();
			this.gPostPro3Check.CanFocus = true;
			this.gPostPro3Check.Name = "gPostPro3Check";
			this.gPostPro3Check.Label = global::Mono.Unix.Catalog.GetString ("Promotor 3");
			this.gPostPro3Check.DrawIndicator = true;
			this.gPostPro3Check.UseUnderline = true;
			this.hbox14.Add (this.gPostPro3Check);
			global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.gPostPro3Check]));
			w104.Position = 0;
			// Container child hbox14.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xpad = 10;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Size (bp): ");
			this.hbox14.Add (this.label9);
			global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label9]));
			w105.Position = 1;
			w105.Expand = false;
			w105.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.gPostPro3Entry = new global::Gtk.Entry ();
			this.gPostPro3Entry.CanFocus = true;
			this.gPostPro3Entry.Name = "gPostPro3Entry";
			this.gPostPro3Entry.IsEditable = true;
			this.gPostPro3Entry.InvisibleChar = '•';
			this.hbox14.Add (this.gPostPro3Entry);
			global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.gPostPro3Entry]));
			w106.Position = 2;
			this.vbox19.Add (this.hbox14);
			global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.vbox19 [this.hbox14]));
			w107.Position = 0;
			w107.Expand = false;
			w107.Fill = false;
			// Container child vbox19.Gtk.Box+BoxChild
			this.vbox20 = new global::Gtk.VBox ();
			this.vbox20.Name = "vbox20";
			this.vbox20.Spacing = 6;
			// Container child vbox20.Gtk.Box+BoxChild
			this.gPostMake3FlankCheck = new global::Gtk.CheckButton ();
			this.gPostMake3FlankCheck.CanFocus = true;
			this.gPostMake3FlankCheck.Name = "gPostMake3FlankCheck";
			this.gPostMake3FlankCheck.Label = global::Mono.Unix.Catalog.GetString ("Generate Non-specific 3' Flank Region");
			this.gPostMake3FlankCheck.Active = true;
			this.gPostMake3FlankCheck.DrawIndicator = true;
			this.gPostMake3FlankCheck.UseUnderline = true;
			this.vbox20.Add (this.gPostMake3FlankCheck);
			global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.vbox20 [this.gPostMake3FlankCheck]));
			w108.Position = 0;
			w108.Expand = false;
			w108.Fill = false;
			// Container child vbox20.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox ();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xpad = 20;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Size (bp): ");
			this.hbox15.Add (this.label10);
			global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label10]));
			w109.Position = 0;
			w109.Expand = false;
			w109.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.gPost3FlankEntry = new global::Gtk.Entry ();
			this.gPost3FlankEntry.CanFocus = true;
			this.gPost3FlankEntry.Name = "gPost3FlankEntry";
			this.gPost3FlankEntry.IsEditable = true;
			this.gPost3FlankEntry.InvisibleChar = '•';
			this.hbox15.Add (this.gPost3FlankEntry);
			global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.gPost3FlankEntry]));
			w110.Position = 1;
			this.vbox20.Add (this.hbox15);
			global::Gtk.Box.BoxChild w111 = ((global::Gtk.Box.BoxChild)(this.vbox20 [this.hbox15]));
			w111.Position = 1;
			w111.Expand = false;
			w111.Fill = false;
			// Container child vbox20.Gtk.Box+BoxChild
			this.vbox21 = new global::Gtk.VBox ();
			this.vbox21.Name = "vbox21";
			this.vbox21.Spacing = 6;
			// Container child vbox21.Gtk.Box+BoxChild
			this.gPostIntronCheck = new global::Gtk.CheckButton ();
			this.gPostIntronCheck.CanFocus = true;
			this.gPostIntronCheck.Name = "gPostIntronCheck";
			this.gPostIntronCheck.Label = global::Mono.Unix.Catalog.GetString ("Label Intronic Regions Between Exons");
			this.gPostIntronCheck.DrawIndicator = true;
			this.gPostIntronCheck.UseUnderline = true;
			this.vbox21.Add (this.gPostIntronCheck);
			global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.vbox21 [this.gPostIntronCheck]));
			w112.Position = 0;
			w112.Expand = false;
			w112.Fill = false;
			this.vbox20.Add (this.vbox21);
			global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.vbox20 [this.vbox21]));
			w113.Position = 2;
			this.vbox19.Add (this.vbox20);
			global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.vbox19 [this.vbox20]));
			w114.Position = 1;
			this.vbox16.Add (this.vbox19);
			global::Gtk.Box.BoxChild w115 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.vbox19]));
			w115.Position = 2;
			this.hbox11.Add (this.vbox16);
			global::Gtk.Box.BoxChild w116 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.vbox16]));
			w116.Position = 0;
			w116.Expand = false;
			w116.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xpad = 5;
			this.label13.Ypad = 5;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Filtering");
			this.label13.Justify = ((global::Gtk.Justification)(2));
			this.vbox10.Add (this.label13);
			global::Gtk.Box.BoxChild w117 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.label13]));
			w117.Position = 0;
			w117.Expand = false;
			w117.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.filterWindow = new global::Gtk.ScrolledWindow ();
			this.filterWindow.CanFocus = true;
			this.filterWindow.Name = "filterWindow";
			this.filterWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.vbox10.Add (this.filterWindow);
			global::Gtk.Box.BoxChild w118 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.filterWindow]));
			w118.Position = 1;
			// Container child vbox10.Gtk.Box+BoxChild
			this.filterRunBut = new global::Gtk.Button ();
			this.filterRunBut.Sensitive = false;
			this.filterRunBut.CanFocus = true;
			this.filterRunBut.Name = "filterRunBut";
			this.filterRunBut.UseUnderline = true;
			this.filterRunBut.Label = global::Mono.Unix.Catalog.GetString ("Run Filtering Now (close Settings)");
			this.vbox10.Add (this.filterRunBut);
			global::Gtk.Box.BoxChild w119 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.filterRunBut]));
			w119.Position = 2;
			w119.Expand = false;
			w119.Fill = false;
			this.hbox11.Add (this.vbox10);
			global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.vbox10]));
			w120.Position = 1;
			this.vbox7.Add (this.hbox11);
			global::Gtk.Box.BoxChild w121 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox11]));
			w121.Position = 0;
			this.notebook1.Add (this.vbox7);
			global::Gtk.Notebook.NotebookChild w122 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox7]));
			w122.Position = 4;
			// Notebook tab
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Genes");
			this.notebook1.SetTabLabel (this.vbox7, this.label11);
			this.label11.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.hbox28 = new global::Gtk.HBox ();
			this.hbox28.Name = "hbox28";
			this.hbox28.Spacing = 6;
			// Container child hbox28.Gtk.Box+BoxChild
			this.vbox30 = new global::Gtk.VBox ();
			this.vbox30.Name = "vbox30";
			this.vbox30.Spacing = 6;
			// Container child vbox30.Gtk.Box+BoxChild
			this.vbox31 = new global::Gtk.VBox ();
			this.vbox31.Name = "vbox31";
			this.vbox31.Spacing = 6;
			// Container child vbox31.Gtk.Box+BoxChild
			this.label30 = new global::Gtk.Label ();
			this.label30.Name = "label30";
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString ("Data Saving:");
			this.vbox31.Add (this.label30);
			global::Gtk.Box.BoxChild w123 = ((global::Gtk.Box.BoxChild)(this.vbox31 [this.label30]));
			w123.Position = 0;
			w123.Expand = false;
			w123.Fill = false;
			w123.Padding = ((uint)(4));
			// Container child vbox31.Gtk.Box+BoxChild
			this.graphOutProcessCheck = new global::Gtk.CheckButton ();
			this.graphOutProcessCheck.CanFocus = true;
			this.graphOutProcessCheck.Name = "graphOutProcessCheck";
			this.graphOutProcessCheck.Label = global::Mono.Unix.Catalog.GetString ("Save-text Outputs Graph Content?");
			this.graphOutProcessCheck.DrawIndicator = true;
			this.graphOutProcessCheck.UseUnderline = true;
			this.vbox31.Add (this.graphOutProcessCheck);
			global::Gtk.Box.BoxChild w124 = ((global::Gtk.Box.BoxChild)(this.vbox31 [this.graphOutProcessCheck]));
			w124.Position = 1;
			w124.Expand = false;
			w124.Fill = false;
			this.vbox30.Add (this.vbox31);
			global::Gtk.Box.BoxChild w125 = ((global::Gtk.Box.BoxChild)(this.vbox30 [this.vbox31]));
			w125.Position = 0;
			w125.Expand = false;
			w125.Fill = false;
			// Container child vbox30.Gtk.Box+BoxChild
			this.label31 = new global::Gtk.Label ();
			this.label31.Name = "label31";
			this.label31.LabelProp = global::Mono.Unix.Catalog.GetString ("This is the difference between saving the graph contents and saving the data used to contruct the graph contents. Check if you just want to re-draw the graph with another tool, uncheck if you want the full data for statistical tests or other puposes..");
			this.label31.Wrap = true;
			this.vbox30.Add (this.label31);
			global::Gtk.Box.BoxChild w126 = ((global::Gtk.Box.BoxChild)(this.vbox30 [this.label31]));
			w126.Position = 1;
			w126.Expand = false;
			w126.Fill = false;
			// Container child vbox30.Gtk.Box+BoxChild
			this.vbox36 = new global::Gtk.VBox ();
			this.vbox36.Name = "vbox36";
			this.vbox36.Spacing = 6;
			// Container child vbox36.Gtk.Box+BoxChild
			this.label35 = new global::Gtk.Label ();
			this.label35.Name = "label35";
			this.label35.LabelProp = global::Mono.Unix.Catalog.GetString ("Base-Image Creation:");
			this.vbox36.Add (this.label35);
			global::Gtk.Box.BoxChild w127 = ((global::Gtk.Box.BoxChild)(this.vbox36 [this.label35]));
			w127.Position = 0;
			w127.Expand = false;
			w127.Fill = false;
			w127.Padding = ((uint)(5));
			// Container child vbox36.Gtk.Box+BoxChild
			this.hbox31 = new global::Gtk.HBox ();
			this.hbox31.Name = "hbox31";
			this.hbox31.Spacing = 6;
			// Container child hbox31.Gtk.Box+BoxChild
			this.vbox37 = new global::Gtk.VBox ();
			this.vbox37.Name = "vbox37";
			this.vbox37.Spacing = 6;
			// Container child vbox37.Gtk.Box+BoxChild
			this.hbox32 = new global::Gtk.HBox ();
			this.hbox32.Name = "hbox32";
			this.hbox32.Spacing = 6;
			// Container child hbox32.Gtk.Box+BoxChild
			this.graphFromEndCheck = new global::Gtk.CheckButton ();
			this.graphFromEndCheck.CanFocus = true;
			this.graphFromEndCheck.Name = "graphFromEndCheck";
			this.graphFromEndCheck.Label = global::Mono.Unix.Catalog.GetString ("Align Features by End-points? (default is by start)");
			this.graphFromEndCheck.DrawIndicator = true;
			this.graphFromEndCheck.UseUnderline = true;
			this.hbox32.Add (this.graphFromEndCheck);
			global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.hbox32 [this.graphFromEndCheck]));
			w128.Position = 0;
			this.vbox37.Add (this.hbox32);
			global::Gtk.Box.BoxChild w129 = ((global::Gtk.Box.BoxChild)(this.vbox37 [this.hbox32]));
			w129.Position = 0;
			w129.Expand = false;
			w129.Fill = false;
			// Container child vbox37.Gtk.Box+BoxChild
			this.hbox33 = new global::Gtk.HBox ();
			this.hbox33.Name = "hbox33";
			this.hbox33.Spacing = 6;
			// Container child hbox33.Gtk.Box+BoxChild
			this.label36 = new global::Gtk.Label ();
			this.label36.Name = "label36";
			this.label36.Xpad = 5;
			this.label36.LabelProp = global::Mono.Unix.Catalog.GetString ("Default Number of Bases to Draw:");
			this.hbox33.Add (this.label36);
			global::Gtk.Box.BoxChild w130 = ((global::Gtk.Box.BoxChild)(this.hbox33 [this.label36]));
			w130.Position = 0;
			w130.Expand = false;
			w130.Fill = false;
			// Container child hbox33.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator ();
			this.hseparator4.Name = "hseparator4";
			this.hbox33.Add (this.hseparator4);
			global::Gtk.Box.BoxChild w131 = ((global::Gtk.Box.BoxChild)(this.hbox33 [this.hseparator4]));
			w131.Position = 1;
			// Container child hbox33.Gtk.Box+BoxChild
			this.graphBasesEntry = new global::Gtk.Entry ();
			this.graphBasesEntry.CanFocus = true;
			this.graphBasesEntry.Name = "graphBasesEntry";
			this.graphBasesEntry.IsEditable = true;
			this.graphBasesEntry.InvisibleChar = '•';
			this.hbox33.Add (this.graphBasesEntry);
			global::Gtk.Box.BoxChild w132 = ((global::Gtk.Box.BoxChild)(this.hbox33 [this.graphBasesEntry]));
			w132.Position = 2;
			this.vbox37.Add (this.hbox33);
			global::Gtk.Box.BoxChild w133 = ((global::Gtk.Box.BoxChild)(this.vbox37 [this.hbox33]));
			w133.Position = 1;
			w133.Expand = false;
			w133.Fill = false;
			this.hbox31.Add (this.vbox37);
			global::Gtk.Box.BoxChild w134 = ((global::Gtk.Box.BoxChild)(this.hbox31 [this.vbox37]));
			w134.Position = 0;
			this.vbox36.Add (this.hbox31);
			global::Gtk.Box.BoxChild w135 = ((global::Gtk.Box.BoxChild)(this.vbox36 [this.hbox31]));
			w135.Position = 1;
			w135.Expand = false;
			w135.Fill = false;
			this.vbox30.Add (this.vbox36);
			global::Gtk.Box.BoxChild w136 = ((global::Gtk.Box.BoxChild)(this.vbox30 [this.vbox36]));
			w136.Position = 2;
			this.hbox28.Add (this.vbox30);
			global::Gtk.Box.BoxChild w137 = ((global::Gtk.Box.BoxChild)(this.hbox28 [this.vbox30]));
			w137.Position = 0;
			this.notebook1.Add (this.hbox28);
			global::Gtk.Notebook.NotebookChild w138 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.hbox28]));
			w138.Position = 5;
			// Notebook tab
			this.label21 = new global::Gtk.Label ();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Graphs");
			this.notebook1.SetTabLabel (this.hbox28, this.label21);
			this.label21.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.hbox29 = new global::Gtk.HBox ();
			this.hbox29.Name = "hbox29";
			this.hbox29.Spacing = 6;
			// Container child hbox29.Gtk.Box+BoxChild
			this.vbox32 = new global::Gtk.VBox ();
			this.vbox32.Name = "vbox32";
			this.vbox32.Spacing = 6;
			// Container child vbox32.Gtk.Box+BoxChild
			this.vbox33 = new global::Gtk.VBox ();
			this.vbox33.Name = "vbox33";
			this.vbox33.Spacing = 6;
			// Container child vbox33.Gtk.Box+BoxChild
			this.label32 = new global::Gtk.Label ();
			this.label32.Name = "label32";
			this.label32.LabelProp = global::Mono.Unix.Catalog.GetString ("Region Analysis Options");
			this.vbox33.Add (this.label32);
			global::Gtk.Box.BoxChild w139 = ((global::Gtk.Box.BoxChild)(this.vbox33 [this.label32]));
			w139.Position = 0;
			w139.Expand = false;
			w139.Fill = false;
			w139.Padding = ((uint)(5));
			// Container child vbox33.Gtk.Box+BoxChild
			this.statsNormVarCheck = new global::Gtk.CheckButton ();
			this.statsNormVarCheck.CanFocus = true;
			this.statsNormVarCheck.Name = "statsNormVarCheck";
			this.statsNormVarCheck.Label = global::Mono.Unix.Catalog.GetString ("Normalise Variant Counts to Region Lengths");
			this.statsNormVarCheck.Active = true;
			this.statsNormVarCheck.DrawIndicator = true;
			this.statsNormVarCheck.UseUnderline = true;
			this.statsNormVarCheck.BorderWidth = ((uint)(5));
			this.vbox33.Add (this.statsNormVarCheck);
			global::Gtk.Box.BoxChild w140 = ((global::Gtk.Box.BoxChild)(this.vbox33 [this.statsNormVarCheck]));
			w140.Position = 1;
			w140.Expand = false;
			w140.Fill = false;
			this.vbox32.Add (this.vbox33);
			global::Gtk.Box.BoxChild w141 = ((global::Gtk.Box.BoxChild)(this.vbox32 [this.vbox33]));
			w141.Position = 0;
			this.hbox29.Add (this.vbox32);
			global::Gtk.Box.BoxChild w142 = ((global::Gtk.Box.BoxChild)(this.hbox29 [this.vbox32]));
			w142.Position = 0;
			w142.Expand = false;
			w142.Fill = false;
			this.notebook1.Add (this.hbox29);
			global::Gtk.Notebook.NotebookChild w143 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.hbox29]));
			w143.Position = 6;
			// Notebook tab
			this.label33 = new global::Gtk.Label ();
			this.label33.Name = "label33";
			this.label33.LabelProp = global::Mono.Unix.Catalog.GetString ("Statistics");
			this.notebook1.SetTabLabel (this.hbox29, this.label33);
			this.label33.ShowAll ();
			this.vbox1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w144 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
			w144.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.mainCancel = new global::Gtk.Button ();
			this.mainCancel.CanFocus = true;
			this.mainCancel.Name = "mainCancel";
			this.mainCancel.UseUnderline = true;
			this.mainCancel.BorderWidth = ((uint)(5));
			this.mainCancel.Label = global::Mono.Unix.Catalog.GetString ("Cancel");
			this.hbox1.Add (this.mainCancel);
			global::Gtk.Box.BoxChild w145 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.mainCancel]));
			w145.Position = 0;
			w145.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.mainAccept = new global::Gtk.Button ();
			this.mainAccept.CanFocus = true;
			this.mainAccept.Name = "mainAccept";
			this.mainAccept.UseUnderline = true;
			this.mainAccept.Xalign = 1F;
			this.mainAccept.Yalign = 1F;
			this.mainAccept.BorderWidth = ((uint)(5));
			this.mainAccept.Label = global::Mono.Unix.Catalog.GetString ("Accept");
			this.hbox1.Add (this.mainAccept);
			global::Gtk.Box.BoxChild w146 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.mainAccept]));
			w146.Position = 1;
			w146.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w147 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w147.Position = 1;
			w147.Expand = false;
			w147.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 767;
			this.DefaultHeight = 367;
			this.Show ();
			this.notebook1.WidgetEvent += new global::Gtk.WidgetEventHandler (this.OnActivity);
			this.filterRunBut.Clicked += new global::System.EventHandler (this.OnRunFilter);
			this.mainCancel.Clicked += new global::System.EventHandler (this.OnMainCancel);
			this.mainAccept.Clicked += new global::System.EventHandler (this.OnAccept);
		}
	}
}
